name: Build, Run and Benchmark quickjs4j and graaljs

on:
  push:
    paths:
      - 'quickjs4j-benchmark/**'
      - 'graaljs-benchmark/**'
  pull_request:
    paths:
      - 'quickjs4j-benchmark/**'
      - 'graaljs-benchmark/**'
  workflow_dispatch:

jobs:
  build-run-benchmark:
    name: Benchmark on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GraalVM Java 24
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24.0.2'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      # Build quickjs4j
      - name: Build quickjs4j-benchmark with Maven
        working-directory: quickjs4j-benchmark
        run: mvn clean package -DskipTests

      - name: List files in quickjs4j-benchmark/target
        working-directory: quickjs4j-benchmark
        run: ls -l target/

      # Build graaljs
      - name: Build graaljs-benchmark with Maven
        working-directory: graaljs-benchmark
        run: mvn clean package -DskipTests

      - name: List files in graaljs-benchmark/target
        working-directory: graaljs-benchmark
        run: ls -l target/

      # Run quickjs4j once to check output
      - name: Run quickjs4j-benchmark once
        working-directory: quickjs4j-benchmark
        run: java -jar target/quickjs4j-benchmark-1.0-SNAPSHOT.jar

      # Run graaljs once to check output
      - name: Run graaljs-benchmark once
        working-directory: graaljs-benchmark
        run: java -jar target/graaljs-benchmark-1.0-SNAPSHOT.jar

      # Install hyperfine for benchmarking (Linux + macOS)
      - name: Install hyperfine
        if: matrix.os != 'windows-latest'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y hyperfine || brew install hyperfine

      # Install hyperfine on Windows
      - name: Install hyperfine on Windows
        if: matrix.os == 'windows-latest'
        run: choco install hyperfine -y

      # Benchmark quickjs4j
      - name: Benchmark quickjs4j-benchmark with hyperfine
        working-directory: quickjs4j-benchmark
        run: hyperfine --show-output 'java -jar target/quickjs4j-benchmark-1.0-SNAPSHOT.jar'

      # Benchmark graaljs
      - name: Benchmark graaljs-benchmark with hyperfine
        working-directory: graaljs-benchmark
        run: hyperfine --show-output 'java -jar target/graaljs-benchmark-1.0-SNAPSHOT.jar'
